name: kirtasite
description: A new flutter module project.





version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  http:
  url_launcher:

  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0




flutter:
  
  
  
  uses-material-design: true

  assets:
    - assets/png/
  
  
  
  
  
  module:
    androidX: true
    androidPackage: com.example.kirtasite
    iosBundleIdentifier: com.example.kirtasite
